### ISSUE TITLE
ERROR in ./node_modules/guid-typescript/src/guid.ts

### ISSUE THREAD

**Issue by ofirrifo** [NicolasDeveloper/guid-typescript#12]
I'm getting this error when I'm executing  `npm run build` in angular cli project

ERROR in ./node_modules/guid-typescript/src/guid.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /.../dev/management/mgmt-console/node_modules/guid-typescript/src/guid.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/.../dev/management/mgmt-console/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:834:23)
    at /.../dev/management/mgmt-console/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by gekkedev** [comment]
I haven't seen your import/require statement, but `node_modules/guid-typescript/src/guid.ts` definitely isn't the right path, as there is not `src` folder in the tarball.
Try importing from `node_modules/guid-typescript/dist/guid.js` instead.

**Comment by shalinsitwala** [comment]
Add "node_modules/guid-typescript/src/guid.ts" to your tsconfig.json "files" array
